[package]
name = "digit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jumprope = "1.0.0"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"
glfw = "0.45.0"
pollster = "0.2"
